In [16]:
 import nltk
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist

In [17]:
pip install Sastrawi

In [18]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [19]:
df=pd.read_csv("news.csv")
df

title  ...   category
0   moeldoko harap seni budaya bisa jadi magnet ku...  ...    Culture
1   seniman palestina sulap tembakan israel jadi k...  ...    Culture
2   sontek cara 56 kreator berpengaruh di dunia ci...  ...    Culture
3   intip pertunjukan fashion dalam balutan seni t...  ...    Culture
4   kenang benyamin sueb teater abnon gelar pement...  ...    Culture
..                                                ...  ...        ...
95           riset.aids.buntu.ilmuwan.dunia.putus.asa  ...  Kesehatan
96        pmi.luncurkan.aliansi.global.untuk.hivaids.  ...  Kesehatan
97    bali.masuk.lima.besar.jumlah.penderita.hivaids.  ...  Kesehatan
98      ketimpangan.gender.jadikan.wanita.rentan.hiv.  ...  Kesehatan
99               hepatitis.b.lebih.infeksius.dari.hiv  ...  Kesehatan

[100 rows x 3 columns]

In [20]:

df = df.dropna()
print(df.shape)

(100, 3)


In [21]:
df

title  ...   category
0   moeldoko harap seni budaya bisa jadi magnet ku...  ...    Culture
1   seniman palestina sulap tembakan israel jadi k...  ...    Culture
2   sontek cara 56 kreator berpengaruh di dunia ci...  ...    Culture
3   intip pertunjukan fashion dalam balutan seni t...  ...    Culture
4   kenang benyamin sueb teater abnon gelar pement...  ...    Culture
..                                                ...  ...        ...
95           riset.aids.buntu.ilmuwan.dunia.putus.asa  ...  Kesehatan
96        pmi.luncurkan.aliansi.global.untuk.hivaids.  ...  Kesehatan
97    bali.masuk.lima.besar.jumlah.penderita.hivaids.  ...  Kesehatan
98      ketimpangan.gender.jadikan.wanita.rentan.hiv.  ...  Kesehatan
99               hepatitis.b.lebih.infeksius.dari.hiv  ...  Kesehatan

[100 rows x 3 columns]

text Preprocessing title

Text Preprocessing text

In [22]:
df['text'] = df['text'].str.lower()
df['text'] = df['text'].str.replace(r'\d+','')
df['text'] = df['text'].str.replace('[^\w\s]','')

In [23]:
df['category'] = df['category'].str.lower()

In [24]:
df

title  ...   category
0   moeldoko harap seni budaya bisa jadi magnet ku...  ...    culture
1   seniman palestina sulap tembakan israel jadi k...  ...    culture
2   sontek cara 56 kreator berpengaruh di dunia ci...  ...    culture
3   intip pertunjukan fashion dalam balutan seni t...  ...    culture
4   kenang benyamin sueb teater abnon gelar pement...  ...    culture
..                                                ...  ...        ...
95           riset.aids.buntu.ilmuwan.dunia.putus.asa  ...  kesehatan
96        pmi.luncurkan.aliansi.global.untuk.hivaids.  ...  kesehatan
97    bali.masuk.lima.besar.jumlah.penderita.hivaids.  ...  kesehatan
98      ketimpangan.gender.jadikan.wanita.rentan.hiv.  ...  kesehatan
99               hepatitis.b.lebih.infeksius.dari.hiv  ...  kesehatan

[100 rows x 3 columns]

Removing Emoji

In [25]:
df.astype(str).apply(lambda x: x.str.encode('ascii', 'ignore').str.decode('ascii'))

title  ...   category
0   moeldoko harap seni budaya bisa jadi magnet ku...  ...    culture
1   seniman palestina sulap tembakan israel jadi k...  ...    culture
2   sontek cara 56 kreator berpengaruh di dunia ci...  ...    culture
3   intip pertunjukan fashion dalam balutan seni t...  ...    culture
4   kenang benyamin sueb teater abnon gelar pement...  ...    culture
..                                                ...  ...        ...
95           riset.aids.buntu.ilmuwan.dunia.putus.asa  ...  kesehatan
96        pmi.luncurkan.aliansi.global.untuk.hivaids.  ...  kesehatan
97    bali.masuk.lima.besar.jumlah.penderita.hivaids.  ...  kesehatan
98      ketimpangan.gender.jadikan.wanita.rentan.hiv.  ...  kesehatan
99               hepatitis.b.lebih.infeksius.dari.hiv  ...  kesehatan

[100 rows x 3 columns]

In [26]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory,StopWordRemover, ArrayDictionary

In [27]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [28]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from nltk.tokenize import word_tokenize
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
factory = StemmerFactory()
stemmer = factory.create_stemmer()
factorya = StopWordRemoverFactory()
stopword = factorya.create_stop_word_remover()
df['text']=df['text'].apply(word_tokenize)
df['text']=df['text'].apply(lambda x: [stemmer.stem(y) for y in x])
df['text']=df['text'].apply(lambda x: [stopword.remove(y) for y in x])


In [29]:
df

title  ...   category
0   moeldoko harap seni budaya bisa jadi magnet ku...  ...    culture
1   seniman palestina sulap tembakan israel jadi k...  ...    culture
2   sontek cara 56 kreator berpengaruh di dunia ci...  ...    culture
3   intip pertunjukan fashion dalam balutan seni t...  ...    culture
4   kenang benyamin sueb teater abnon gelar pement...  ...    culture
..                                                ...  ...        ...
95           riset.aids.buntu.ilmuwan.dunia.putus.asa  ...  kesehatan
96        pmi.luncurkan.aliansi.global.untuk.hivaids.  ...  kesehatan
97    bali.masuk.lima.besar.jumlah.penderita.hivaids.  ...  kesehatan
98      ketimpangan.gender.jadikan.wanita.rentan.hiv.  ...  kesehatan
99               hepatitis.b.lebih.infeksius.dari.hiv  ...  kesehatan

[100 rows x 3 columns]

In [30]:
save=df
save

title  ...   category
0   moeldoko harap seni budaya bisa jadi magnet ku...  ...    culture
1   seniman palestina sulap tembakan israel jadi k...  ...    culture
2   sontek cara 56 kreator berpengaruh di dunia ci...  ...    culture
3   intip pertunjukan fashion dalam balutan seni t...  ...    culture
4   kenang benyamin sueb teater abnon gelar pement...  ...    culture
..                                                ...  ...        ...
95           riset.aids.buntu.ilmuwan.dunia.putus.asa  ...  kesehatan
96        pmi.luncurkan.aliansi.global.untuk.hivaids.  ...  kesehatan
97    bali.masuk.lima.besar.jumlah.penderita.hivaids.  ...  kesehatan
98      ketimpangan.gender.jadikan.wanita.rentan.hiv.  ...  kesehatan
99               hepatitis.b.lebih.infeksius.dari.hiv  ...  kesehatan

[100 rows x 3 columns]

Combine text and title

In [31]:
df["edited"]=df["text"]

In [32]:
for i in range(len(df['category'])) :
  if df['category'][i] == 'culture':
    df['category'][i]=1
  else :
    df['category'][i]=0

In [33]:
df

title  ...                                             edited
0   moeldoko harap seni budaya bisa jadi magnet ku...  ...  [kepala, staf, presiden, ri, jenderal, tni, pu...
1   seniman palestina sulap tembakan israel jadi k...  ...  [beda, , seniman, , umum, orang, seniman, majd...
2   sontek cara 56 kreator berpengaruh di dunia ci...  ...  [jadi, modal, utama, , , milik, tiap, orang, ,...
3   intip pertunjukan fashion dalam balutan seni t...  ...  [, sabang, , merauke, indonesia, tawar, indah,...
4   kenang benyamin sueb teater abnon gelar pement...  ...  [benyamin, suaeb, bukan, , sekadar, nama, soso...
..                                                ...  ...                                                ...
95           riset.aids.buntu.ilmuwan.dunia.putus.asa  ...  [empat, abad, sejak, virus, , aids, temu, upay...
96        pmi.luncurkan.aliansi.global.untuk.hivaids.  ...  [palang, merah, indonesia, pmi, , federasi, in...
97    bali.masuk.lima.besar.jumlah.penderita.hivaids.  ...  [derita, hivaids, , bal, cara, kumulatif, hing...
98      ketimpangan.gender.jadikan.wanita.rentan.hiv.  ...  [ikat, perempuan, positif, indonesia, ippi, bu...
99               hepatitis.b.lebih.infeksius.dari.hiv  ...  [lama, , , akrab, , istilah, hiv, , kenal, san...

[100 rows x 4 columns]

In [34]:
filter = df['category'] == '1'
dfcul = df[filter]
dfkes = df[~filter]

In [37]:
dfcul = dfcul['edited']
dfcul

Series([], Name: edited, dtype: object)

In [38]:
dfkes = dfkes['edited']
dfkes

0     [kepala, staf, presiden, ri, jenderal, tni, pu...
1     [beda, , seniman, , umum, orang, seniman, majd...
2     [jadi, modal, utama, , , milik, tiap, orang, ,...
3     [, sabang, , merauke, indonesia, tawar, indah,...
4     [benyamin, suaeb, bukan, , sekadar, nama, soso...
                            ...                        
95    [empat, abad, sejak, virus, , aids, temu, upay...
96    [palang, merah, indonesia, pmi, , federasi, in...
97    [derita, hivaids, , bal, cara, kumulatif, hing...
98    [ikat, perempuan, positif, indonesia, ippi, bu...
99    [lama, , , akrab, , istilah, hiv, , kenal, san...
Name: edited, Length: 100, dtype: object

In [41]:
def get_all_words(dataset):
    allword=[]
    for i in dataset:
        for y in i:
            allword.append(y)
    return allword
    
all_cul_words = get_all_words(dfcul)
all_kes_words = get_all_words(dfkes)
allword= get_all_words(df['edited'])

In [42]:
allword

['kepala',
 'staf',
 'presiden',
 'ri',
 'jenderal',
 'tni',
 'purn',
 'dr',
 'moeldoko',
 'hadir',
 'pementasa',
 'judul',
 'langit',
 'bidadari',
 '',
 'gedung',
 'teater',
 'garuda',
 'taman',
 'mini',
 'indonesia',
 'indah',
 'jakarta',
 'tepat',
 '',
 'ingat',
 'hari',
 'lahir',
 'pancasila',
 'juni',
 '',
 'sempat',
 'sebut',
 'moeldoko',
 'ingat',
 'seluruh',
 'generasi',
 'bangsa',
 'betapa',
 'kaya',
 'budaya',
 '',
 'milik',
 '',
 'indonesialebih',
 'lanjut',
 'kaya',
 'budaya',
 '',
 'turut',
 'moeldoko',
 '',
 'jadi',
 'instrumen',
 '',
 'tarik',
 'minat',
 'wisatawan',
 'maupun',
 'investor',
 '',
 'luar',
 'negeri',
 '',
 'unjung',
 '',
 'kembang',
 'bisnis',
 '',
 'indonesiabaca',
 'jugadatanglah',
 '',
 'jamin',
 '',
 'wisatawan',
 '',
 'aman',
 '',
 'nyaman',
 'nikmat',
 'indonesia',
 '',
 'investor',
 '',
 'aman',
 'investasi',
 '',
 'indonesia',
 'ungkap',
 'moeldokodalam',
 'bagai',
 'sempat',
 'temu',
 '',
 'banyak',
 'tokoh',
 '',
 'banyak',
 'pihak',
 'moeldoko',

In [43]:
from gensim.models import Word2Vec 

# Create CBOW model 
model = Word2Vec([allword], min_count = 1, size = 100, window = 5)
#setup the parameter of the model one by1
print(model.wv.vocab)
print(model.wv.syn0)
print(model.wv.syn0.shape)

filename="word2vecembedding.txt"
model.wv.save_word2vec_format(filename,binary=False)

{'kepala': <gensim.models.keyedvectors.Vocab object at 0x7ff85c669e48>, 'staf': <gensim.models.keyedvectors.Vocab object at 0x7ff85c669eb8>, 'presiden': <gensim.models.keyedvectors.Vocab object at 0x7ff804eb3a20>, 'ri': <gensim.models.keyedvectors.Vocab object at 0x7ff804eb3be0>, 'jenderal': <gensim.models.keyedvectors.Vocab object at 0x7ff8046abd68>, 'tni': <gensim.models.keyedvectors.Vocab object at 0x7ff803448390>, 'purn': <gensim.models.keyedvectors.Vocab object at 0x7ff8034486a0>, 'dr': <gensim.models.keyedvectors.Vocab object at 0x7ff80300d6d8>, 'moeldoko': <gensim.models.keyedvectors.Vocab object at 0x7ff802fb51d0>, 'hadir': <gensim.models.keyedvectors.Vocab object at 0x7ff802fb5208>, 'pementasa': <gensim.models.keyedvectors.Vocab object at 0x7ff802fb5240>, 'judul': <gensim.models.keyedvectors.Vocab object at 0x7ff802fb5278>, 'langit': <gensim.models.keyedvectors.Vocab object at 0x7ff802fb52b0>, 'bidadari': <gensim.models.keyedvectors.Vocab object at 0x7ff802fb52e8>, '': <gensim

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  


In [44]:
import os
embeddings_index = {}
f= open(os.path.join('','word2vecembedding.txt'),encoding="utf-8")
for line in f:
  values = line.split()
  word = values[0]
  coefs= np.asarray(values[1:])
  embeddings_index[word]=coefs
f.close()

In [45]:
from tensorflow.python.keras.preprocessing.text import Tokenizer
from tensorflow.python.keras.preprocessing.sequence import pad_sequences

tokenizer_obj = Tokenizer()
tokenizer_obj.fit_on_texts(df['edited'])
total_reviews = df['edited'].values

sequences = tokenizer_obj.texts_to_sequences(df['edited'])

max_length = max([len(i) for i in total_reviews])
print(max_length)


#pad
word_index= tokenizer_obj.word_index
review_pad = pad_sequences(sequences,maxlen=max_length)
sentiment = df['category'].values
print(review_pad)
print(sentiment.shape)

#define vocab size
vocab_size = len(tokenizer_obj.word_index)+1
print(vocab_size)


1553
[[   0    0    0 ...   76   77   78]
 [   0    0    0 ...   76   77   78]
 [   0    0    0 ...   76   77   78]
 ...
 [   0    0    0 ...    8  131 1651]
 [   0    0    0 ...    1 2295   79]
 [   0    0    0 ...   83  595  146]]
(100,)
5049


In [46]:
num_words = len(word_index)+1
embedding_matrix = np.zeros((num_words,100))
for word, i in word_index.items():
  if i>num_words:
    continue
  embedding_vector = embeddings_index.get(word)
  if embedding_vector is not None:
    embedding_matrix[i] = embedding_vector

In [47]:
print(num_words)

5049


In [49]:
pip install keras_metrics

In [50]:
from keras import Sequential
from keras.layers import Dense,Embedding,LSTM,GRU
from keras.layers.embeddings import Embedding
import keras_metrics

EMBEDDING_DIM = 100

model= Sequential()
model.add(Embedding(vocab_size,EMBEDDING_DIM,input_length=max_length))
model.add(GRU(units=32, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy',keras_metrics.precision(), keras_metrics.recall(),keras_metrics.f1_score()])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 1553, 100)         504900    
_________________________________________________________________
gru (GRU)                    (None, 32)                12864     
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 517,797
Trainable params: 517,797
Non-trainable params: 0
_________________________________________________________________


In [51]:
VALIDATION_SPLIT = 0.4
indices=np.arange(review_pad.shape[0])

review_pad = review_pad[indices]
sentiment = sentiment[indices]
num_validation_samples = int (VALIDATION_SPLIT*review_pad.shape[0])
x_train_pad = review_pad[:-num_validation_samples]
y_train = sentiment[:-num_validation_samples]
x_test_pad = review_pad[-num_validation_samples:]
y_test = sentiment[-num_validation_samples:]

print(x_train_pad.shape)
print(y_train.shape)
print(x_test_pad.shape)
print(y_test.shape)


(60, 1553)
(60,)
(40, 1553)
(40,)


In [53]:
y_train = np.asarray(y_train).astype('float32')
y_test = np.asarray(y_test).astype('float32')

In [54]:
print("Train...")
themodel = model.fit(x_train_pad,y_train, epochs= 10, validation_data=(x_test_pad,y_test),verbose=2)

Train...
Epoch 1/10


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:1402: UserWarning: `layer.updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`layer.updates` will be removed in a future version. '


2/2 - 9s - loss: 0.6577 - accuracy: 0.8833 - precision: 0.8580 - recall: 1.0000 - f1_score: 0.9234 - val_loss: 0.7068 - val_accuracy: 0.1500 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_f1_score: 0.0000e+00
Epoch 2/10
2/2 - 4s - loss: 0.6298 - accuracy: 0.8833 - precision: 0.8741 - recall: 1.0000 - f1_score: 0.9328 - val_loss: 0.7164 - val_accuracy: 0.0000e+00 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_f1_score: 0.0000e+00
Epoch 3/10
2/2 - 4s - loss: 0.5985 - accuracy: 0.9000 - precision: 0.8964 - recall: 1.0000 - f1_score: 0.9454 - val_loss: 0.7263 - val_accuracy: 0.0000e+00 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_f1_score: 0.0000e+00
Epoch 4/10
2/2 - 4s - loss: 0.5706 - accuracy: 0.8667 - precision: 0.8988 - recall: 1.0000 - f1_score: 0.9463 - val_loss: 0.7368 - val_accuracy: 0.0000e+00 - val_precision: 0.0000e+00 - val_recall: 0.0000e+00 - val_f1_score: 0.0000e+00
Epoch 5/10
2/2 - 4s - loss: 0.5379 - accuracy: 0.9000 - precision: 0.89

Berdasarkan hasil di atas dapat dilihat bahwa hasil accuracy yang hasilkan cukup besar yaitu