In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import statsmodels.formula.api as sm
import seaborn as sns


data = pd.read_csv('E202-COMP7117-TD01-00 - classification.csv')

for i in range(len(data)):
  if data['free sulfur dioxide'][i] == 'High':
    data['free sulfur dioxide'][i] = 3
  elif data['free sulfur dioxide'][i] == 'Medium':
    data['free sulfur dioxide'][i] = 2
  elif data['free sulfur dioxide'][i] == 'Low':
    data['free sulfur dioxide'][i] = 1
  else:
    data['free sulfur dioxide'][i] = 0

  if data['density'][i] == 'Very High':
    data['density'][i] = 0
  elif data['density'][i] == 'High':
    data['density'][i] = 3
  elif data['density'][i] == 'Medium':
    data['density'][i] = 2
  elif data['density'][i] == 'Low':
    data['density'][i] = 1

  if data['pH'][i] == 'Very Basic':
    data['pH'][i] = 3
  elif data['pH'][i] == 'Normal':
    data['pH'][i] = 2
  elif data['pH'][i] == 'Very Acidic':
    data['pH'][i] = 1
  else:
    data['pH'][i] = 0

  if data['quality'][i] == 'Great':
    data['quality'][i] = 4
  elif data['quality'][i] == 'Good':
    data['quality'][i] = 3
  elif data['quality'][i] == 'Fine':
    data['quality'][i] = 2
  elif data['quality'][i] == 'Decent':
    data['quality'][i] = 1
  elif data['quality'][i] == 'Fair':
    data['quality'][i] = 0
  

data

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:24: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:31: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:46: Settin

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol quality
0               7.4             0.700         0.00  ...       0.56      9.4       1
1               7.8             0.880         0.00  ...       0.68      9.8       1
2               7.8             0.760         0.04  ...       0.65      9.8       1
3              11.2             0.280         0.56  ...       0.58      9.8       2
4               7.4             0.700         0.00  ...       0.56      9.4       1
...             ...               ...          ...  ...        ...      ...     ...
1594            6.2             0.600         0.08  ...       0.58     10.5       1
1595            5.9             0.550         0.10  ...       0.76     11.2       2
1596            6.3             0.510         0.13  ...       0.75     11.0       2
1597            5.9             0.645         0.12  ...       0.71     10.2       1
1598            6.0             0.310         0.47  ...       0.66     11.0       2

[1599 rows x 12 columns]

In [ ]:
x_data = data[['volatile acidity','chlorides','free sulfur dioxide','total sulfur dioxide','density','pH','sulphates','alcohol','quality']]
y_data = data[['quality']]

In [ ]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import MinMaxScaler,OneHotEncoder


scaler = MinMaxScaler()
x_data = scaler.fit_transform(x_data)

encoder = OneHotEncoder(sparse=False)
y_data = encoder.fit_transform(y_data)

print(x_data)

pca = PCA(n_components=4)
pca = pca.fit(x_data)
x_data = pca.transform(x_data)
print(x_data)

[[4.89501047e-04 1.06844741e-01 6.66666667e-01 ... 1.37724551e-01
  1.04529617e-10 2.50000000e-01]
 [6.41415164e-04 1.43572621e-01 0.00000000e+00 ... 2.09580838e-01
  1.46341464e-10 2.50000000e-01]
 [5.40139086e-04 1.33555927e-01 1.00000000e+00 ... 1.91616766e-01
  1.46341464e-10 2.50000000e-01]
 ...
 [3.29147255e-04 1.06844741e-01 0.00000000e+00 ... 2.51497006e-01
  2.71777004e-10 5.00000000e-01]
 [4.43082844e-04 1.05175292e-01 0.00000000e+00 ... 2.27544910e-01
  1.88153310e-10 2.50000000e-01]
 [1.60353791e-04 9.18196995e-02 1.00000000e+00 ... 1.97604790e-01
  2.71777004e-10 5.00000000e-01]]
[[-0.57285975 -0.16813245 -0.30570376 -0.10814055]
 [-0.14611975 -0.6990872   0.01924523 -0.11891464]
 [-0.70890063  0.12802033  0.03543444 -0.14457143]
 ...
 [ 0.13357461 -0.49477846 -0.0244123   0.12746846]
 [ 0.3453453  -0.34929354 -0.41945239 -0.11823672]
 [-0.15736447  0.51368088 -0.06692951  0.06974029]]


In [ ]:
import tensorflow.compat.v1 as tf
from sklearn.model_selection import train_test_split


tf.disable_v2_behavior()


layer = {
    'input' : 4,
    'hidden' : 6,
    'output' : 5
}

weight = {
    'to_hidden' : tf.Variable(tf.random_normal([layer['input'],layer['hidden']])),
    'to_output' : tf.Variable(tf.random_normal([layer['hidden'],layer['output']]))
}

bias = {
    'to_hidden' : tf.Variable(tf.random_normal([layer['hidden']])),
    'to_output' : tf.Variable(tf.random_normal([layer['output']]))
}


x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size= .1, train_size=0.7)

#dia random terus ambil 20% di test 80% di train
x_validation, _, y_validation, _ = train_test_split(x_train, y_train, train_size=.2)

x = tf.placeholder(tf.float32, [None, layer['input']])
target = tf.placeholder(tf.float32, [None,layer['output']])

def predict():
    wx_b1= tf.matmul(x, weight['to_hidden']) + bias['to_hidden']
    y1= tf.nn.sigmoid(wx_b1)

    wx_b2= tf.matmul(y1, weight['to_output']) + bias['to_output']
    y2= tf.nn.sigmoid(wx_b2)
    return y2

y= predict()
epoch = 5000
alpha = 0.5

error = tf.reduce_mean(0.5 * (target - y) **2)
optimizer = tf.train.GradientDescentOptimizer(alpha)
train = optimizer.minimize(error)

with tf.Session() as sess: 
    sess.run(tf.global_variables_initializer())
    valid = 0
    for i in range(1, epoch+1):
        sess.run(train, feed_dict={x: x_train,target: y_train})
        if i % 100 == 0:
            print("Epoch: {}    Error: {}".format(i, 
                sess.run(error, feed_dict={
                    x: x_train,
                    target: y_train
                })
            ))
        if i % 500 == 0:
            currentvalid = tf.reduce_mean(.5 * (target - y) ** 2)
            print(' Validation Error: {}%'.format(
                sess.run(currentvalid, feed_dict={
                    x: x_validation,
                    target: y_validation
                })
            ))

            if i == 500 or tf.math.greater(validation_error, curr_validation_error) is not None:
                validation_error = currentvalid
                tf.train.Saver().save(sess, 'check/checkpoint{}.ckpt'.format(i))

    # Evaluation
    true_prediction = tf.equal(tf.argmax(y, axis=1), tf.argmax(target, axis=1))
    accuracy = tf.reduce_mean(tf.cast(true_prediction, tf.float32)) * 100
    print('Accuracy: {}%'.format(
        sess.run(accuracy, feed_dict={
            x: x_test,
            target: y_test
        })
    ))


Epoch: 100    Error: 0.13857059180736542
Epoch: 200    Error: 0.09188803285360336
Epoch: 300    Error: 0.06998276710510254
Epoch: 400    Error: 0.06597976386547089
Epoch: 500    Error: 0.06521552801132202
 Validation Error: 0.06495848298072815%
Epoch: 600    Error: 0.06460673362016678
Epoch: 700    Error: 0.06406119465827942
Epoch: 800    Error: 0.06355230510234833
Epoch: 900    Error: 0.0630660131573677
Epoch: 1000    Error: 0.06259343773126602
 Validation Error: 0.061872851103544235%
Epoch: 1100    Error: 0.06212849169969559
Epoch: 1200    Error: 0.06166679784655571
Epoch: 1300    Error: 0.06120512634515762
Epoch: 1400    Error: 0.06074093282222748
Epoch: 1500    Error: 0.06027235835790634
 Validation Error: 0.059112779796123505%
Epoch: 1600    Error: 0.05979795753955841
Epoch: 1700    Error: 0.0593167245388031
Epoch: 1800    Error: 0.058827996253967285
Epoch: 1900    Error: 0.05833140388131142
Epoch: 2000    Error: 0.05782681331038475
 Validation Error: 0.05621599778532982%
Epoch: 2