1 A

In [ ]:
 import nltk
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist

In [ ]:
pip install Sastrawi

     |████████████████████████████████| 215kB 5.2MB/s 


In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [ ]:
df=pd.read_csv("news.csv")
df

title  ...   category
0   moeldoko harap seni budaya bisa jadi magnet ku...  ...    Culture
1   seniman palestina sulap tembakan israel jadi k...  ...    Culture
2   sontek cara 56 kreator berpengaruh di dunia ci...  ...    Culture
3   intip pertunjukan fashion dalam balutan seni t...  ...    Culture
4   kenang benyamin sueb teater abnon gelar pement...  ...    Culture
..                                                ...  ...        ...
95           riset.aids.buntu.ilmuwan.dunia.putus.asa  ...  Kesehatan
96        pmi.luncurkan.aliansi.global.untuk.hivaids.  ...  Kesehatan
97    bali.masuk.lima.besar.jumlah.penderita.hivaids.  ...  Kesehatan
98      ketimpangan.gender.jadikan.wanita.rentan.hiv.  ...  Kesehatan
99               hepatitis.b.lebih.infeksius.dari.hiv  ...  Kesehatan

[100 rows x 3 columns]

In [ ]:

df = df.dropna()
print(df.shape)

(100, 3)


In [ ]:
df

title  ...   category
0   moeldoko harap seni budaya bisa jadi magnet ku...  ...    Culture
1   seniman palestina sulap tembakan israel jadi k...  ...    Culture
2   sontek cara 56 kreator berpengaruh di dunia ci...  ...    Culture
3   intip pertunjukan fashion dalam balutan seni t...  ...    Culture
4   kenang benyamin sueb teater abnon gelar pement...  ...    Culture
..                                                ...  ...        ...
95           riset.aids.buntu.ilmuwan.dunia.putus.asa  ...  Kesehatan
96        pmi.luncurkan.aliansi.global.untuk.hivaids.  ...  Kesehatan
97    bali.masuk.lima.besar.jumlah.penderita.hivaids.  ...  Kesehatan
98      ketimpangan.gender.jadikan.wanita.rentan.hiv.  ...  Kesehatan
99               hepatitis.b.lebih.infeksius.dari.hiv  ...  Kesehatan

[100 rows x 3 columns]

Text Preprocessing

In [ ]:
df['text'] = df['text'].str.lower()
df['text'] = df['text'].str.replace(r'\d+','')
df['text'] = df['text'].str.replace('[^\w\s]','')

In [ ]:
df['category'] = df['category'].str.lower()

In [ ]:
df

title  ...   category
0   moeldoko harap seni budaya bisa jadi magnet ku...  ...    culture
1   seniman palestina sulap tembakan israel jadi k...  ...    culture
2   sontek cara 56 kreator berpengaruh di dunia ci...  ...    culture
3   intip pertunjukan fashion dalam balutan seni t...  ...    culture
4   kenang benyamin sueb teater abnon gelar pement...  ...    culture
..                                                ...  ...        ...
95           riset.aids.buntu.ilmuwan.dunia.putus.asa  ...  kesehatan
96        pmi.luncurkan.aliansi.global.untuk.hivaids.  ...  kesehatan
97    bali.masuk.lima.besar.jumlah.penderita.hivaids.  ...  kesehatan
98      ketimpangan.gender.jadikan.wanita.rentan.hiv.  ...  kesehatan
99               hepatitis.b.lebih.infeksius.dari.hiv  ...  kesehatan

[100 rows x 3 columns]

Removing Emoji

In [ ]:
df.astype(str).apply(lambda x: x.str.encode('ascii', 'ignore').str.decode('ascii'))

title  ...   category
0   moeldoko harap seni budaya bisa jadi magnet ku...  ...    culture
1   seniman palestina sulap tembakan israel jadi k...  ...    culture
2   sontek cara 56 kreator berpengaruh di dunia ci...  ...    culture
3   intip pertunjukan fashion dalam balutan seni t...  ...    culture
4   kenang benyamin sueb teater abnon gelar pement...  ...    culture
..                                                ...  ...        ...
95           riset.aids.buntu.ilmuwan.dunia.putus.asa  ...  kesehatan
96        pmi.luncurkan.aliansi.global.untuk.hivaids.  ...  kesehatan
97    bali.masuk.lima.besar.jumlah.penderita.hivaids.  ...  kesehatan
98      ketimpangan.gender.jadikan.wanita.rentan.hiv.  ...  kesehatan
99               hepatitis.b.lebih.infeksius.dari.hiv  ...  kesehatan

[100 rows x 3 columns]

In [ ]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory,StopWordRemover, ArrayDictionary

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [ ]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from nltk.tokenize import word_tokenize
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
factory = StemmerFactory()
stemmer = factory.create_stemmer()
factorya = StopWordRemoverFactory()
stopword = factorya.create_stop_word_remover()
df['text']=df['text'].apply(word_tokenize)
df['text']=df['text'].apply(lambda x: [stemmer.stem(y) for y in x])
df['text']=df['text'].apply(lambda x: [stopword.remove(y) for y in x])


In [ ]:
df

title  ...   category
0   moeldoko harap seni budaya bisa jadi magnet ku...  ...    culture
1   seniman palestina sulap tembakan israel jadi k...  ...    culture
2   sontek cara 56 kreator berpengaruh di dunia ci...  ...    culture
3   intip pertunjukan fashion dalam balutan seni t...  ...    culture
4   kenang benyamin sueb teater abnon gelar pement...  ...    culture
..                                                ...  ...        ...
95           riset.aids.buntu.ilmuwan.dunia.putus.asa  ...  kesehatan
96        pmi.luncurkan.aliansi.global.untuk.hivaids.  ...  kesehatan
97    bali.masuk.lima.besar.jumlah.penderita.hivaids.  ...  kesehatan
98      ketimpangan.gender.jadikan.wanita.rentan.hiv.  ...  kesehatan
99               hepatitis.b.lebih.infeksius.dari.hiv  ...  kesehatan

[100 rows x 3 columns]

In [ ]:
save=df
save

title  ...   category
0   moeldoko harap seni budaya bisa jadi magnet ku...  ...    culture
1   seniman palestina sulap tembakan israel jadi k...  ...    culture
2   sontek cara 56 kreator berpengaruh di dunia ci...  ...    culture
3   intip pertunjukan fashion dalam balutan seni t...  ...    culture
4   kenang benyamin sueb teater abnon gelar pement...  ...    culture
..                                                ...  ...        ...
95           riset.aids.buntu.ilmuwan.dunia.putus.asa  ...  kesehatan
96        pmi.luncurkan.aliansi.global.untuk.hivaids.  ...  kesehatan
97    bali.masuk.lima.besar.jumlah.penderita.hivaids.  ...  kesehatan
98      ketimpangan.gender.jadikan.wanita.rentan.hiv.  ...  kesehatan
99               hepatitis.b.lebih.infeksius.dari.hiv  ...  kesehatan

[100 rows x 3 columns]

Change Culture to 1 and Kesehatan to 0

In [ ]:
for i in range(len(df['category'])) :
  if df['category'][i] == 'culture':
    df['category'][i]=1
  else :
    df['category'][i]=0

In [ ]:
df['edited']=df['text']

Getting all the words

In [ ]:
filter = df['category'] == '1'
dfcul = df[filter]
dfkes = df[~filter]

In [ ]:
dfcul = dfcul['edited']
dfcul

Series([], Name: edited, dtype: object)

In [ ]:
dfkes = dfkes['edited']
dfkes

0     [kepala, staf, presiden, ri, jenderal, tni, pu...
1     [beda, , seniman, , umum, orang, seniman, majd...
2     [jadi, modal, utama, , , milik, tiap, orang, ,...
3     [, sabang, , merauke, indonesia, tawar, indah,...
4     [benyamin, suaeb, bukan, , sekadar, nama, soso...
                            ...                        
95    [empat, abad, sejak, virus, , aids, temu, upay...
96    [palang, merah, indonesia, pmi, , federasi, in...
97    [derita, hivaids, , bal, cara, kumulatif, hing...
98    [ikat, perempuan, positif, indonesia, ippi, bu...
99    [lama, , , akrab, , istilah, hiv, , kenal, san...
Name: text, Length: 100, dtype: object

In [ ]:
def get_all_words(dataset):
    allword=[]
    for i in dataset:
        for y in i:
            allword.append(y)
    return allword
    
all_cul_words = get_all_words(dfcul)
all_kes_words = get_all_words(dfkes)
allword= get_all_words(df['edited'])

In [ ]:
allword

['kepala',
 'staf',
 'presiden',
 'ri',
 'jenderal',
 'tni',
 'purn',
 'dr',
 'moeldoko',
 'hadir',
 'pementasa',
 'judul',
 'langit',
 'bidadari',
 '',
 'gedung',
 'teater',
 'garuda',
 'taman',
 'mini',
 'indonesia',
 'indah',
 'jakarta',
 'tepat',
 '',
 'ingat',
 'hari',
 'lahir',
 'pancasila',
 'juni',
 '',
 'sempat',
 'sebut',
 'moeldoko',
 'ingat',
 'seluruh',
 'generasi',
 'bangsa',
 'betapa',
 'kaya',
 'budaya',
 '',
 'milik',
 '',
 'indonesialebih',
 'lanjut',
 'kaya',
 'budaya',
 '',
 'turut',
 'moeldoko',
 '',
 'jadi',
 'instrumen',
 '',
 'tarik',
 'minat',
 'wisatawan',
 'maupun',
 'investor',
 '',
 'luar',
 'negeri',
 '',
 'unjung',
 '',
 'kembang',
 'bisnis',
 '',
 'indonesiabaca',
 'jugadatanglah',
 '',
 'jamin',
 '',
 'wisatawan',
 '',
 'aman',
 '',
 'nyaman',
 'nikmat',
 'indonesia',
 '',
 'investor',
 '',
 'aman',
 'investasi',
 '',
 'indonesia',
 'ungkap',
 'moeldokodalam',
 'bagai',
 'sempat',
 'temu',
 '',
 'banyak',
 'tokoh',
 '',
 'banyak',
 'pihak',
 'moeldoko',

Using Word 2 Vec

Word2vec is a two layer neural network that is trained to change word into vector so that the words can be understand by a deep learning model.
  From a large corpus of word it will produce a vector space, with each unique  word in a corpus being assign a vector in the space.
  Using a neural network word2vec take input as one-hot vectors, which is a vector with the same length, filled with zero excepet the index that represent the word we want to repesent, assign "1".

the rows of hidden layer weight matrix, are actually the word vector, it operates as a lookup table. The output, is just a word vector of the input word.

and the output layer is just a softmax activation function.


In [ ]:
from gensim.models import Word2Vec 

# Create CBOW model 
model = Word2Vec([allword], min_count = 1, size = 100, window = 5)
#setup the parameter of the model one by1
print(model.wv.vocab)
print(model.wv.syn0)
print(model.wv.syn0.shape)

filename="word2vecembedding.txt"
model.wv.save_word2vec_format(filename,binary=False)

{'kepala': <gensim.models.keyedvectors.Vocab object at 0x7fc1d6bdaa20>, 'staf': <gensim.models.keyedvectors.Vocab object at 0x7fc234d4ec88>, 'presiden': <gensim.models.keyedvectors.Vocab object at 0x7fc234d4ecf8>, 'ri': <gensim.models.keyedvectors.Vocab object at 0x7fc1d6bc8ef0>, 'jenderal': <gensim.models.keyedvectors.Vocab object at 0x7fc1d6625550>, 'tni': <gensim.models.keyedvectors.Vocab object at 0x7fc1d588dac8>, 'purn': <gensim.models.keyedvectors.Vocab object at 0x7fc1d588ddd8>, 'dr': <gensim.models.keyedvectors.Vocab object at 0x7fc1d5447e80>, 'moeldoko': <gensim.models.keyedvectors.Vocab object at 0x7fc1d53f2978>, 'hadir': <gensim.models.keyedvectors.Vocab object at 0x7fc1d53f29b0>, 'pementasa': <gensim.models.keyedvectors.Vocab object at 0x7fc1d53f29e8>, 'judul': <gensim.models.keyedvectors.Vocab object at 0x7fc1d53f2a20>, 'langit': <gensim.models.keyedvectors.Vocab object at 0x7fc1d53f2a58>, 'bidadari': <gensim.models.keyedvectors.Vocab object at 0x7fc1d53f2a90>, '': <gensim

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  


read the "word2vecembedding.txt" and take the value,word, and the index.

In [ ]:
import os
embeddings_index = {}
f= open(os.path.join('','word2vecembedding.txt'),encoding="utf-8")
for line in f:
  values = line.split()
  word = values[0]
  coefs= np.asarray(values[1:])
  embeddings_index[word]=coefs
f.close()

In [ ]:
len(embeddings_index)

5049

Using keras we take tokenzier and fit the transformed dataset and using pad_sequences we pad the vector so that all of the input have the same width of vector.

In [ ]:
from tensorflow.python.keras.preprocessing.text import Tokenizer
from tensorflow.python.keras.preprocessing.sequence import pad_sequences

tokenizer_obj = Tokenizer()
tokenizer_obj.fit_on_texts(df['edited'])
total_reviews = df['edited'].values

sequences = tokenizer_obj.texts_to_sequences(df['edited'])

max_length = max([len(i) for i in total_reviews])
print(max_length)


#pad
word_index= tokenizer_obj.word_index
review_pad = pad_sequences(sequences,maxlen=max_length)
sentiment = df['category'].values
print(review_pad)
print(sentiment.shape)

#define vocab size
vocab_size = len(tokenizer_obj.word_index)+1
print(vocab_size)


1553
[[   0    0    0 ...   76   77   78]
 [   0    0    0 ...   76   77   78]
 [   0    0    0 ...   76   77   78]
 ...
 [   0    0    0 ...    8  131 1651]
 [   0    0    0 ...    1 2295   79]
 [   0    0    0 ...   83  595  146]]
(100,)
5049


Form all of the matrix above, we transform the word into vector form the word2vec data by picking the corresponding index. 

In [ ]:
num_words = len(word_index)+1
embedding_matrix = np.zeros((num_words,100))
for word, i in word_index.items():
  if i>num_words:
    continue
  embedding_vector = embeddings_index.get(word)
  if embedding_vector is not None:
    embedding_matrix[i] = embedding_vector

In [ ]:
print(num_words)

5049


In [ ]:
pip install keras_metrics

These are the BPNN model using keras, in keras the model automaticly use BPNN so we only need to specify the model, the input layer consist of how many the length is and for the hidden layer we use 32 hidden layer. And 1 dense layer of the output.

In [ ]:
from keras import Sequential
from keras.layers import Dense,Embedding,LSTM,GRU
from keras.layers.embeddings import Embedding
import keras_metrics

EMBEDDING_DIM = 100

model= Sequential()
model.add(Embedding(vocab_size,EMBEDDING_DIM,input_length=max_length))
model.add(GRU(units=32, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy',keras_metrics.precision(), keras_metrics.recall(),keras_metrics.f1_score()])

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 1553, 100)         504900    
_________________________________________________________________
gru (GRU)                    (None, 32)                12864     
_________________________________________________________________
dense (Dense)                (None, 16)                528       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 17        
Total params: 518,309
Trainable params: 518,309
Non-trainable params: 0
_________________________________________________________________


spliting the data into 70% trainning
30% testing

In [ ]:
VALIDATION_SPLIT = 0.3
indices=np.arange(review_pad.shape[0])

review_pad = review_pad[indices]
sentiment = sentiment[indices]
num_validation_samples = int (VALIDATION_SPLIT*review_pad.shape[0])
x_train_pad = review_pad[:-num_validation_samples]
y_train = sentiment[:-num_validation_samples]
x_test_pad = review_pad[-num_validation_samples:]
y_test = sentiment[-num_validation_samples:]

print(x_train_pad.shape)
print(y_train.shape)
print(x_test_pad.shape)
print(y_test.shape)


(70, 1553)
(70,)
(30, 1553)
(30,)


In [ ]:
review_pad.shape

(100, 1553)

In [ ]:
sentiment.shape

(100,)

In [ ]:
x_cul=review_pad[:49]
y_cul=sentiment[:49]

In [ ]:
x_kes=review_pad[50:]
y_kes=sentiment[50:]

In [ ]:
x_train=x_cul[:30]
y_train=y_cul[:30]

In [ ]:
x_train.shape

(30, 1553)

In [ ]:
y_train.shape

(30,)

In [ ]:
x_test=x_cul[31:]
y_test=y_cul[31:]

In [ ]:
x_test.shape

(18, 1553)

In [ ]:
y_test.shape

(18,)

In [ ]:
x_train = np.append(x_train,x_kes[:30],axis=0)
y_train = np.append(y_train,y_kes[:30],axis=0)

In [ ]:
x_train.shape

(60, 1553)

In [ ]:
y_train.shape

(60,)

In [ ]:
x_test = np.append(x_test,x_kes[31:],axis=0)
y_test = np.append(y_test,y_kes[31:],axis=0)

In [ ]:
x_test.shape

(37, 1553)

In [ ]:
y_test.shape

(37,)

In [ ]:
y_train = np.asarray(y_train).astype('float32')
y_test = np.asarray(y_test).astype('float32')

In [ ]:
print("Train...")
themodel = model.fit(x_train,y_train, epochs= 10, validation_data=(x_test,y_test))

Train...
Epoch 1/10


/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py:1402: UserWarning: `layer.updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`layer.updates` will be removed in a future version. '


2/2 [==============================] - 9s 3s/step - loss: 0.6996 - accuracy: 0.2729 - precision: 0.0417 - recall: 0.0222 - f1_score: 0.0290 - val_loss: 0.6893 - val_accuracy: 0.8378 - val_precision: 0.7841 - val_recall: 1.0000 - val_f1_score: 0.8786
Epoch 2/10
2/2 [==============================] - 4s 2s/step - loss: 0.6878 - accuracy: 0.8486 - precision: 0.7193 - recall: 1.0000 - f1_score: 0.8358 - val_loss: 0.6834 - val_accuracy: 0.9189 - val_precision: 0.8571 - val_recall: 1.0000 - val_f1_score: 0.9231
Epoch 3/10
2/2 [==============================] - 4s 2s/step - loss: 0.6792 - accuracy: 0.9785 - precision: 0.9522 - recall: 1.0000 - f1_score: 0.9755 - val_loss: 0.6769 - val_accuracy: 0.9189 - val_precision: 0.8571 - val_recall: 1.0000 - val_f1_score: 0.9231
Epoch 4/10
2/2 [==============================] - 4s 2s/step - loss: 0.6689 - accuracy: 1.0000 - precision: 1.0000 - recall: 1.0000 - f1_score: 1.0000 - val_loss: 0.6692 - val_accuracy: 0.9459 - val_precision: 0.9000 - val_recal

1 B

Berdasarkan hasil di atas dapat dilihat bahwa hasil accuracy yang hasilkan cukup besar yang dimana hasil ini cukup akurat.
Kita juga dapat melihat dimana hasil precision dari model di atas 1 yang dimana berarti semua yang di jalankan mendapatkan hasil yang sama.
kemudian pada val accuracy dapat di lihat nilainya 1 yang dimana menunjukkan bahwa modelnya sangat akurat.

1 C

Dari model deep learning di atas sangatlah simple yang dimana menggunakan word2vec kemudian digabungkan dengan model Connected Layer yang dimana input layernya merupakan berapa banyak kata yang ada dan hidden layer yang berjumlah 32 kemudian dengan 2 dense layer.

Source

https://medium.com/@ksnugroho/dasar-text-preprocessing-dengan-python-a4fa52608ffe

https://medium.com/@datamonsters/text-preprocessing-in-python-steps-tools-and-examples-bf025f872908

https://www.digitalocean.com/community/tutorials/how-to-perform-sentiment-analysis-in-python-3-using-the-natural-language-toolkit-nltk

https://www.geeksforgeeks.org/python-word-embedding-using-word2vec/

https://www.kaggle.com/pierremegret/gensim-word2vec-tutorial

https://towardsdatascience.com/machine-learning-word-embedding-sentiment-classification-using-keras-b83c28087456

https://israelg99.github.io/2017-03-23-Word2Vec-Explained/
