In [2]:
 import nltk
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist

In [3]:
pip install Sastrawi

     |████████████████████████████████| 215kB 6.0MB/s 


In [4]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [5]:
df = pd.read_csv('hatespeech.txt', sep='\t', header=None,encoding='windows-1252')

In [6]:
df.columns = ["Label","Tweet"]

In [7]:
df

Label                                              Tweet
0     Label                                              Tweet
1    Non_HS  RT @spardaxyz: Fadli Zon Minta Mendagri Segera...
2    Non_HS  RT @baguscondromowo: Mereka terus melukai aksi...
3    Non_HS  Sylvi: bagaimana gurbernur melakukan kekerasan...
4    Non_HS  Ahmad Dhani Tak Puas Debat Pilkada, Masalah Ja...
..      ...                                                ...
709      HS  Muka Si BABi Ahok Tuh Yg Mirip SERBET Lantai.....
710      HS  Betul bang hancurkan merka bang, musnahkan chi...
711      HS  Sapa Yg bilang Ahok anti korupsi!?, klo grombo...
712      HS  Gw juga ngimpi SENTILIN BIJI BABI AHOK, pcetar...
713      HS  Mudah2an gw ketemu sama SI BABI IWAN BOPENG DI...

[714 rows x 2 columns]

In [8]:
df=df.drop(df.index[0])

In [9]:
df=df.reset_index(drop=True)

In [10]:
df

Label                                              Tweet
0    Non_HS  RT @spardaxyz: Fadli Zon Minta Mendagri Segera...
1    Non_HS  RT @baguscondromowo: Mereka terus melukai aksi...
2    Non_HS  Sylvi: bagaimana gurbernur melakukan kekerasan...
3    Non_HS  Ahmad Dhani Tak Puas Debat Pilkada, Masalah Ja...
4    Non_HS  RT @lisdaulay28: Waspada KTP palsu.....kawal P...
..      ...                                                ...
708      HS  Muka Si BABi Ahok Tuh Yg Mirip SERBET Lantai.....
709      HS  Betul bang hancurkan merka bang, musnahkan chi...
710      HS  Sapa Yg bilang Ahok anti korupsi!?, klo grombo...
711      HS  Gw juga ngimpi SENTILIN BIJI BABI AHOK, pcetar...
712      HS  Mudah2an gw ketemu sama SI BABI IWAN BOPENG DI...

[713 rows x 2 columns]

In [11]:
df = df.dropna()
print(df.shape)

(713, 2)


In [12]:
df['Tweet'] = df['Tweet'].str.lower()
df['Tweet'] = df['Tweet'].str.replace(r'\d+','')
df['Tweet'] = df['Tweet'].str.replace('[^\w\s]','')

In [13]:
df

Label                                              Tweet
0    Non_HS  rt spardaxyz fadli zon minta mendagri segera m...
1    Non_HS  rt baguscondromowo mereka terus melukai aksi d...
2    Non_HS  sylvi bagaimana gurbernur melakukan kekerasan ...
3    Non_HS  ahmad dhani tak puas debat pilkada masalah jal...
4    Non_HS  rt lisdaulay waspada ktp palsukawal pilkada ht...
..      ...                                                ...
708      HS  muka si babi ahok tuh yg mirip serbet lantaiba...
709      HS  betul bang hancurkan merka bang musnahkan chin...
710      HS  sapa yg bilang ahok anti korupsi klo grombolan...
711      HS  gw juga ngimpi sentilin biji babi ahok pcetar ...
712      HS  mudahan gw ketemu sama si babi iwan bopeng di ...

[713 rows x 2 columns]

In [14]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory,StopWordRemover, ArrayDictionary

In [15]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [16]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory
from nltk.tokenize import word_tokenize
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
factory = StemmerFactory()
stemmer = factory.create_stemmer()
factorya = StopWordRemoverFactory()
stopword = factorya.create_stop_word_remover()
df['Tweet']=df['Tweet'].apply(word_tokenize)
df['Tweet']=df['Tweet'].apply(lambda x: [stemmer.stem(y) for y in x])
df['Tweet']=df['Tweet'].apply(lambda x: [stopword.remove(y) for y in x])


In [17]:
df

Label                                              Tweet
0    Non_HS  [rt, spardaxyz, fadli, zon, minta, mendagri, s...
1    Non_HS  [rt, baguscondromowo, , terus, luka, aksi, , r...
2    Non_HS  [sylvi, bagaimana, gurbernur, laku, keras, per...
3    Non_HS  [ahmad, dhani, tak, puas, debat, pilkada, masa...
4    Non_HS  [rt, lisdaulay, waspada, ktp, palsukawal, pilk...
..      ...                                                ...
708      HS  [muka, si, babi, ahok, tuh, yg, mirip, serbet,...
709      HS  [betul, bang, hancur, merka, bang, musnah, chi...
710      HS  [sapa, yg, bilang, ahok, anti, korupsi, klo, g...
711      HS  [gw, , ngimpi, sentilin, biji, babi, ahok, pce...
712      HS  [mudah, gw, ketemu, sama, si, babi, iwan, bope...

[713 rows x 2 columns]

In [18]:
from sklearn import preprocessing

In [19]:
encoder =  preprocessing.LabelEncoder()
encoder.fit(df["Label"])
encoded_Y = encoder.transform(df["Label"])

In [20]:
df["Label"]=encoded_Y

In [21]:
df

Label                                              Tweet
0        1  [rt, spardaxyz, fadli, zon, minta, mendagri, s...
1        1  [rt, baguscondromowo, , terus, luka, aksi, , r...
2        1  [sylvi, bagaimana, gurbernur, laku, keras, per...
3        1  [ahmad, dhani, tak, puas, debat, pilkada, masa...
4        1  [rt, lisdaulay, waspada, ktp, palsukawal, pilk...
..     ...                                                ...
708      0  [muka, si, babi, ahok, tuh, yg, mirip, serbet,...
709      0  [betul, bang, hancur, merka, bang, musnah, chi...
710      0  [sapa, yg, bilang, ahok, anti, korupsi, klo, g...
711      0  [gw, , ngimpi, sentilin, biji, babi, ahok, pce...
712      0  [mudah, gw, ketemu, sama, si, babi, iwan, bope...

[713 rows x 2 columns]

In [22]:
filter = df['Label'] == 1
dfNoHS = df[filter]
dfHS = df[~filter]

In [23]:
dfNoHS

Label                                              Tweet
0        1  [rt, spardaxyz, fadli, zon, minta, mendagri, s...
1        1  [rt, baguscondromowo, , terus, luka, aksi, , r...
2        1  [sylvi, bagaimana, gurbernur, laku, keras, per...
3        1  [ahmad, dhani, tak, puas, debat, pilkada, masa...
4        1  [rt, lisdaulay, waspada, ktp, palsukawal, pilk...
..     ...                                                ...
448      1        [, nama, tuhan, , jakarta, yg, lebih, baik]
449      1  [semagat, buat, pak, anies, moga, selalu, , ra...
450      1  [semua, warga, dki, , hak, pilihmujangan, taku...
451      1  [moga, tuhan, beri, seluruh, masyarakat, dki, ...
452      1  [eks, dukung, agussylvi, , jakarta, timur, dek...

[453 rows x 2 columns]

In [24]:
dfHS

Label                                              Tweet
453      0  [, , salah, jokowi, ahok, , kafirkafir, ateis,...
454      0  [fahmiabuazzam, biar, aja, biar, tai, nya, ken...
455      0  [rt, bungwinar, angin, memporakporandakan, bas...
456      0  [rt, lupuz, prestasi, ahok, nselain, mjadi, ma...
457      0  [ulama, kompak, nyata, harampemimpinkafir, pil...
..     ...                                                ...
708      0  [muka, si, babi, ahok, tuh, yg, mirip, serbet,...
709      0  [betul, bang, hancur, merka, bang, musnah, chi...
710      0  [sapa, yg, bilang, ahok, anti, korupsi, klo, g...
711      0  [gw, , ngimpi, sentilin, biji, babi, ahok, pce...
712      0  [mudah, gw, ketemu, sama, si, babi, iwan, bope...

[260 rows x 2 columns]

In [25]:
def get_all_words(dataset):
    allword=[]
    for i in dataset:
        for y in i:
            allword.append(y)
    return allword
    
all_HS_words = get_all_words(dfHS)
all_NoHS_words = get_all_words(dfNoHS)
allword= get_all_words(df['Tweet'])

In [26]:
allword

['rt',
 'spardaxyz',
 'fadli',
 'zon',
 'minta',
 'mendagri',
 'segera',
 'nonaktif',
 'ahok',
 'jadi',
 'gubernur',
 'dki',
 'httpstcokhvirwpdo',
 'rt',
 'baguscondromowo',
 '',
 'terus',
 'luka',
 'aksi',
 '',
 'rangka',
 'penjara',
 'ahok',
 '',
 'ahok',
 'gagal',
 '',
 'pilkada',
 'sylvi',
 'bagaimana',
 'gurbernur',
 'laku',
 'keras',
 'perempuan',
 'bukti',
 'banyak',
 'ibu',
 'mau',
 'foto',
 'bareng',
 'debatfinalpilkadajkt',
 'ahmad',
 'dhani',
 'tak',
 'puas',
 'debat',
 'pilkada',
 'masalah',
 'jalan',
 '',
 'bekas',
 '',
 'sempat',
 'ungkap',
 'httpstcomhoppluidu',
 'rt',
 'lisdaulay',
 'waspada',
 'ktp',
 'palsukawal',
 'pilkada',
 'httpstcooooerqvsm',
 'felixsiauw',
 '',
 'bnyak',
 '',
 'agam',
 'yg',
 '',
 'bahas',
 '',
 '',
 'pilkada',
 'terus',
 'apa',
 'tingkat',
 'iman',
 '',
 'cuma',
 'batas',
 'pilkada',
 'saidaqil',
 'apa',
 'maksud',
 'nyata',
 '',
 'apa',
 '',
 'amin',
 'kriminalisasi',
 'ahok',
 'hati',
 'jg',
 'dg',
 'mulut',
 'pak',
 'httpstcohodvaymd',
 'aho

In [27]:
from gensim.models import Word2Vec 

# Create CBOW model 
model = Word2Vec([allword], min_count = 1, size = 100, window = 5)
#setup the parameter of the model one by1
print(model.wv.vocab)
print(model.wv.syn0)
print(model.wv.syn0.shape)

filename="word2vecembedding.txt"
model.wv.save_word2vec_format(filename,binary=False)

{'rt': <gensim.models.keyedvectors.Vocab object at 0x7f9090a9fe80>, 'spardaxyz': <gensim.models.keyedvectors.Vocab object at 0x7f90e7afbcf8>, 'fadli': <gensim.models.keyedvectors.Vocab object at 0x7f90e7afbd68>, 'zon': <gensim.models.keyedvectors.Vocab object at 0x7f9090f79fd0>, 'minta': <gensim.models.keyedvectors.Vocab object at 0x7f908fd6e908>, 'mendagri': <gensim.models.keyedvectors.Vocab object at 0x7f908efe2ef0>, 'segera': <gensim.models.keyedvectors.Vocab object at 0x7f908eff1208>, 'nonaktif': <gensim.models.keyedvectors.Vocab object at 0x7f908eb30278>, 'ahok': <gensim.models.keyedvectors.Vocab object at 0x7f908eb48d30>, 'jadi': <gensim.models.keyedvectors.Vocab object at 0x7f908eb48d68>, 'gubernur': <gensim.models.keyedvectors.Vocab object at 0x7f908eb48da0>, 'dki': <gensim.models.keyedvectors.Vocab object at 0x7f908eb48dd8>, 'httpstcokhvirwpdo': <gensim.models.keyedvectors.Vocab object at 0x7f908eb48e10>, 'baguscondromowo': <gensim.models.keyedvectors.Vocab object at 0x7f908eb

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  import sys
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: Call to deprecated `syn0` (Attribute will be removed in 4.0.0, use self.wv.vectors instead).
  


In [32]:
import os
embeddings_index = {}
f= open(os.path.join('','word2vecembedding.txt'),encoding="utf-8")
for line in f:
  values = line.split()
  word = values[0]
  coefs= np.asarray(values[1:])
  embeddings_index[word]=coefs
f.close()

In [33]:
len(embeddings_index)

2580

In [34]:
from tensorflow.python.keras.preprocessing.text import Tokenizer
from tensorflow.python.keras.preprocessing.sequence import pad_sequences

tokenizer_obj = Tokenizer()
tokenizer_obj.fit_on_texts(df['Tweet'])
total_reviews = df['Tweet'].values

sequences = tokenizer_obj.texts_to_sequences(df['Tweet'])

max_length = max([len(i) for i in total_reviews])
print(max_length)


#pad
word_index= tokenizer_obj.word_index
review_pad = pad_sequences(sequences,maxlen=max_length)
sentiment = df['Label'].values
print(review_pad)
print(sentiment.shape)

#define vocab size
vocab_size = len(tokenizer_obj.word_index)+1
print(vocab_size)


30
[[   0    0    0 ...   34   13  969]
 [   0    0    0 ...  279    1   10]
 [   0    0    0 ...  451  609    6]
 ...
 [   0    0    0 ...  347  457  604]
 [   0    0    0 ... 2586  130  911]
 [   0    0    0 ...   22   77    2]]
(713,)
2587


In [35]:
num_words = len(word_index)+1
embedding_matrix = np.zeros((num_words,100))
for word, i in word_index.items():
  if i>num_words:
    continue
  embedding_vector = embeddings_index.get(word)
  if embedding_vector is not None:
    embedding_matrix[i] = embedding_vector

ValueError: ignored

In [ ]:
embedding_matrix.shape

In [ ]:
embedding_vector.shape

In [ ]:
word

In [ ]:
embeddings_index.get(word).shape

In [ ]:
print(num_words)

In [ ]:
pip install keras_metrics

In [ ]:
from keras import Sequential
from keras.layers import Dense,Embedding,LSTM,GRU
from keras.layers.embeddings import Embedding
import keras_metrics

EMBEDDING_DIM = 100

model= Sequential()
model.add(Embedding(vocab_size,EMBEDDING_DIM,input_length=max_length))
model.add(GRU(units=32, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy',keras_metrics.precision(), keras_metrics.recall(),keras_metrics.f1_score()])

model.summary()

In [ ]:
VALIDATION_SPLIT = 0.3
indices=np.arange(review_pad.shape[0])

review_pad = review_pad[indices]
sentiment = sentiment[indices]
num_validation_samples = int (VALIDATION_SPLIT*review_pad.shape[0])
x_train_pad = review_pad[:-num_validation_samples]
y_train = sentiment[:-num_validation_samples]
x_test_pad = review_pad[-num_validation_samples:]
y_test = sentiment[-num_validation_samples:]

print(x_train_pad.shape)
print(y_train.shape)
print(x_test_pad.shape)
print(y_test.shape)


In [ ]:
df_train_NoHS, df_test_NoHS = train_test_split(dfNoHS, test_size=0.2)

In [ ]:
dfNoHS.shape

In [ ]:
dfHS.shape

In [ ]:
x_NoHS = review_pad[:453]
y_NoHS = sentiment[:453]
x_HS = review_pad[454:]
y_HS = sentiment[454:]


In [ ]:
y_HS

In [ ]:
dfHS.shape

In [ ]:
x_test=x_NoHS[:227]
y_test=y_NoHS[:227]
x_test=np.append(x_test,x_HS[:130],axis=0)
y_test=np.append(y_test,y_HS[:130],axis=0)

In [ ]:
y_test.shape

In [ ]:
x_train=x_NoHS[228:]
y_train=y_NoHS[228:]
x_train=np.append(x_train,x_HS[131:],axis=0)
y_train=np.append(y_train,y_HS[131:],axis=0)

In [ ]:
y_train.shape

In [ ]:
print("Train...")
themodel = model.fit(x_train,y_train, epochs= 10, validation_data=(x_test,y_test))